### ISSUE TITLE
/f access

### ISSUE THREAD

**Issue by KAMKEEL** [redstone/LegacyFactions#10]
I've seen this been used on several faction servers as a way to combat this. /f access allows the Leader or Mod, to Access a player to a specific land owned chunk/claim. It is very helpful and is used in CosmicPVP's Custom FactionUUID.

**Comment by MarkehMe** [comment]
Can you explain this a little further? As I don't quite understand what you mean :) thanks!

**Comment by MarkehMe** [comment]
Over a month without a response. I'm going to assume this isn't wanted, and I don't understand the feature idea :(
