### ISSUE TITLE
Allow the Disabling of /F Top to Allow other plugins to override. 

### ISSUE THREAD

**Issue by KAMKEEL** [redstone/LegacyFactions#11]
Some players do not require or desire the functional variety of the current /f top. Allowing plugins such as

- https://www.spigotmc.org/resources/new-update-factions-top-f-top-for-factionsuuid-massivecore-factions.16249/

- https://www.spigotmc.org/resources/f-top-factions-top-by-novucs.26905/

**Comment by MarkehMe** [comment]
Other plugins can easily remove the command, but I will work with the developers to add support. :) 

I've requested it here https://github.com/novucs/factions-top/issues/30

**Comment by MarkehMe** [comment]
@novucs has noted that [support has been added.](https://github.com/novucs/factions-top/issues/30#issuecomment-310098872)
