### ISSUE TITLE
/f top (GUI)

### ISSUE THREAD

**Issue by Idan330I** [redstone/LegacyFactions#114]
F top Idea with filter options and adding a spawner count top. All informations in the video: https://www.youtube.com/watch?v=FdpzxfEtSB8&feature=youtu.be
Hope you like it!

**Comment by MarkehMe** [comment]
Thanks! :)

**Comment by MarkehMe** [comment]
We've added integration with FactionsTop in 1.4.5 which allows you to use the `/f top gui`

https://www.spigotmc.org/resources/f-top-factions-top-by-novucs.26905/
