### ISSUE TITLE
Is there DeluxeChat support?

### ISSUE THREAD

**Issue by Idan330I** [redstone/LegacyFactions#118]
I dont think there is DeluxeChat support could you add that?

**Comment by MarkehMe** [comment]
In what sense?

PlaceholderAPI is used by DeluxeChat - so you can use placeholders.

Does DeluxeChat have channels? I could look into that

**Comment by MarkehMe** [comment]
Okay they use PlaceholderAPI so if you want relational placeholders you will have to ask them to implement it :)

**Comment by Idan330I** [comment]
Hmm my bad tought of another thing
