### ISSUE TITLE
/f truce 

### ISSUE THREAD

**Issue by KAMKEEL** [redstone/LegacyFactions#12]
Adding the Functionality of Truces and Truce Chat into LegacyFactions. In configs allow a customizable permission for these different relations.

**Comment by MarkehMe** [comment]
Truces are already in, and so is truce chat. 

Could you elaborate on what you mean? :)

**Comment by MarkehMe** [comment]
Weird, I see that there is no `/f truce` command now. My misunderstanding!

**Comment by Spazzinq** [comment]
Will you add truce chat to the rotation of /f chat? Like if you use /f c it goes through the chat options but truce is missing.

**Comment by MarkehMe** [comment]
Yep, it's already there I believe.

**Comment by ctooley17** [comment]
Completed in #31

**Comment by MarkehMe** [comment]
🎉 Will be in the next release!
