### ISSUE TITLE
RankQuest by xu_yukun

### ISSUE THREAD

**Issue by dan330330** [redstone/LegacyFactions#124]
https://www.spigotmc.org/resources/rankquests-extremely-configurable-1-7-10-1-12-1.26072/updates
Added support for your plugin. I asked for it you can add it to the supported by `plugins` list ;) 
![screenshot_2017-08-14-21-27-54](https://user-images.githubusercontent.com/29695049/29288236-5013ef78-8138-11e7-9a7b-ef383e187beb.png)

**Comment by MarkehMe** [comment]
Awesome! Thanks, i'll add it now.

🕺
