### ISSUE TITLE
Relation Chat

### ISSUE THREAD

**Issue by KAMKEEL** [redstone/LegacyFactions#13]
Relation chat is not showing to the player, only visible in console.

**Comment by MarkehMe** [comment]
Oh no.

Are you using a chat manager? Could you share your conf.json file?

**Comment by KAMKEEL** [comment]
Unless, Essentials Chat 1.7.10 is causing this I don't really know. Other than that there is no Chat Manager. I'll try resetting the config and let you know.

**Comment by MarkehMe** [comment]
Could you share your conf.json file? :)

**Comment by KAMKEEL** [comment]
I removed my conf.json already... .-.

**Comment by MarkehMe** [comment]
Sadly, it's very hard to diagnose the issue without the conf.json file. 😞 

I can't seem to replicate this :( but if you try again and share your conf.json file I should be able to help you a little more! :) 

Also your server version too, because may it only occurs in certain versions :)
