### ISSUE TITLE
/f admin,mod,ecc... (NOGUI)

### ISSUE THREAD

**Issue by Idan330I** [redstone/LegacyFactions#141]
Makes a notification in title like the thing added in 1.8 that brings up a message that covers all of your screen so all the faction members just of that faction would see it!
#CanIBeLikeAnIdeasAdminForYourPlugins=P @Idan330I

**Comment by MarkehMe** [comment]
Can you elaborate a little more? Not sure I fully understand :)

**Comment by Idan330I** [comment]
Yes i know my english is not the best. I wanna say the /title text and it would say who is the new leader and mod of the faction! Sorry didnt remember the command name ;)
