### ISSUE TITLE
*Bug with unclaiming radius + Power  loss*

### ISSUE THREAD

**Issue by WhichOnez** [redstone/LegacyFactions#147]
If you do /f unclaim 4 (or any radius) it only unclaims the chunk you are standinging in:
https://pastebin.com/e0SKru6P

None of my players lose their power.

**Comment by WhichOnez** [comment]
Another error:
when you /f who unknown player.
https://pastebin.com/4ygL3rzN

**Comment by MarkehMe** [comment]
Thanks for reporting!

**Comment by MarkehMe** [comment]
I have attempted to claim and unclaim in a radius of 4 and it has worked: https://pastebin.com/ZdqmzKHK

Can you give the output of `/f debug` please.

Also do you have `factions.claim.radius`?

**Comment by MarkehMe** [comment]
Unknown player bug has been fixed. :)

**Comment by MarkehMe** [comment]
Perhaps this was fixed in the dev build. I will close it for now, please try the dev build on discord in #testers and see if it is still an issue!

**Comment by WhichOnez** [comment]
factions.claim.radius doesn't work still.
