### ISSUE TITLE
Factions Chat

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#15]
I noticed a bug, Factions chat is not working.

http://prntscr.com/fbm1bd

My config: https://hastebin.com/pifoyekeji.json
Server version: Paper spigot 1.11.2

Yes i am using a chat formatter but it worked fine on factionsuuid before i switched.

**Comment by MarkehMe** [comment]
Thanks for reporting! 

Could you share the console log for this?

**Comment by DuckCraftPvP** [comment]
there is none, Nothing shows in console related to it.

**Comment by DuckCraftPvP** [comment]
Also im using chatcontrol pro incase u need to test.

**Comment by MarkehMe** [comment]
**Fixed in v1.3.0**

https://github.com/redstone/LegacyFactions/releases/tag/v1.3.0
