### ISSUE TITLE
[Suggestion] Faction Emblems

### ISSUE THREAD

**Issue by Buddhano** [redstone/LegacyFactions#161]
Hey :) Me and my staff think it would be great if Factions could choose an "emblem" to represent their faction in the chat. This way our chat wouldn't be overwhelmed with the player's faction, ranks, and name. I feel this would be a nice placeholder and a good addition to the plugin. 

Emblems could be 1-4 letters/symbols long and the player could type out their emblem on their own, for example: /f emblem [Y] would make their emblem in chat [Y] Playername

A more complicated alternative would be to make emblems predefined in the configs and allow players to choose from a list of them.

I also think it would be nice if players could click on emblems in chat to show them information on the faction (make it run /f who basically)

Thanks for your time! 

-Max

**Comment by MarkehMe** [comment]
Sounds like a really cool idea :)
