### ISSUE TITLE
Dynmap Intergration

### ISSUE THREAD

**Issue by DrNer0** [redstone/LegacyFactions#169]
Dynmap is still available in conf but when enabled, no visible difference to dynmap map

**Comment by MarkehMe** [comment]
I think I've heard people were having problems with this 😨 

The current implementation is sloppy and I'll need to rewrite it

**Comment by MarkehMe** [comment]
It also know works with factions faction placeholders 😁 

```
    "description": "<div class=\"infowindow\">\n<span style=\"font-weight: bold; font-size: 150%;\">%factions_faction_name%</span></br>\n<span style=\"font-style: italic; font-size: 110%;\">%factions_faction_description_blankwild%</span></br>\n</br>\n<span style=\"font-weight: bold;\">Leader:</span> %factions_faction_admin%</br>\n<span style=\"font-weight: bold;\">Members:</span> %factions_faction_count_members%</br>\n</div>",
```
<img width="414" alt="screen shot 2017-09-04 at 10 13 30 pm" src="https://user-images.githubusercontent.com/1357323/30026025-80e6204e-91be-11e7-9655-245b20ea66b7.png">
