### ISSUE TITLE
Alphanumeric Problem

### ISSUE THREAD

**Issue by mcmaxcn** [redstone/LegacyFactions#170]
I found a bug in the lastest version 1.4.2.I can use some chinese words,and that will make server stop responding.And after restart server,The faction's name will become 123.

![image](https://i.loli.net/2017/08/26/59a159b7a963a.png)

**Comment by MarkehMe** [comment]
Can you share your `conf.json` file please?

**Comment by mcmaxcn** [comment]
I use default config

**Comment by MarkehMe** [comment]
Please find this section in your conf.json file:

```json
  "enabledScriptSupport": {
    "BALINESE": false,
    "KHMER": false,
    "ARABIC": false,
    "HAN": false
  },
```

Change:
```json
    "HAN": false
```

To:

```json
    "HAN": true
```

This will enable Chinese, Japanese and Korean characters. 

Can you let me know how that goes?

**Comment by mcmaxcn** [comment]
Thanks,it works.

**Comment by MarkehMe** [comment]
Enjoy. Sorry, I will work on documenting that!

**Comment by mcmaxcn** [comment]
The server will not stop responding,but still notice me faction tag can't be shorter than 3 chars.the plugin is awsome,but factions mode is not popular in China,I think if this promble solved,more Chinese will use this plugin.And thanks for add Chinese language.

**Comment by MarkehMe** [comment]
Sorry I don't understand 😢 

Do you want a small character count? You can change it like this:

```json
  "factionTagLengthMin": 1,
```

**Comment by mcmaxcn** [comment]
This is only valid for English and numbers.

**Comment by MarkehMe** [comment]
Can you double check your `conf.json` file and see if `"HAN": true` still?

**Comment by mcmaxcn** [comment]
I also restart server(not plugman)
![image](https://i.loli.net/2017/08/26/59a1647fc64f6.png)

**Comment by MarkehMe** [comment]
Can you please set:

```json
  "factionTagLengthMin": 1,
```

And then type:

```
/f reload
```

**Comment by mcmaxcn** [comment]
Sorry,I forgot.
![image](https://i.loli.net/2017/08/26/59a165708bcc2.png)

**Comment by MarkehMe** [comment]
Can you copy that command and paste it here? That way I can copy and paste to test.

**Comment by MarkehMe** [comment]
Okay, I found a solution.

Set:
```
  "factionTagLengthMin": 0,
```

Then type:
```
/f reload
```

or use command:
```
/f conf factionTagLengthMin 0
```

**Comment by mcmaxcn** [comment]
Yes,finally solve this problem,thanks again.

**Comment by MarkehMe** [comment]
@mcmaxcn can you help me translate some documentation?

I want to translate:
https://github.com/redstone/LegacyFactions/wiki/Multilingual-Script-Support:-English

Into Chinese

**Comment by mcmaxcn** [comment]
Sure.But i found another promble,If I use Chinese language file,It notices me that tag is already in use.
![image](https://i.loli.net/2017/08/26/59a16befb2040.png)

**Comment by MarkehMe** [comment]
@mcmaxcn what is the correct translation for this?

**Comment by mcmaxcn** [comment]
Not a translation problem.I can't create a Chinese name for the faction if i use zh_CN.yml.I think the promble comes from the translation group.

**Comment by mcmaxcn** [comment]
Oh,I found a solution.
![image](https://i.loli.net/2017/08/26/59a170e9d7a0a.png)

**Comment by MarkehMe** [comment]
Oh okay :) I misunderstood, sorry

**Comment by mcmaxcn** [comment]
OK.If i translate "wilderness" into Chinese,I can't create a fation,because it told me that tag is in use.

**Comment by mcmaxcn** [comment]
只要是Java Unicode支持的字符,LegacyFaction都可以支持,你可以在这个网站里找到一个完整的值的列表：

https://docs.oracle.com/javase/8/docs/api/java/lang/Character.UnicodeScript.html

打开你的config.json文件,找到enabledScriptSupport这一段.LegacyFactions默认已经添加了一些变量:

  "enabledScriptSupport": {
    "BALINESE": false,
    "KHMER": false,
    "ARABIC": false,
    "HAN": false
  },

如果要允许巴黎语字符,你需要把默认的值flase改成true.再举个例子,如果要允许阿拉伯字符有需要把默认的值false改成true,就像这样：

  "enabledScriptSupport": {
    "BALINESE": false,
    "KHMER": false,
    "ARABIC": true,
    "HAN": false
  },

如果你想要的脚本类型没有列出来,很简单,只要把”BALINESE”换成你想要的脚本类型.举个例子,如果你想用希腊语：

  "enabledScriptSupport": {
    "GREEK": true,
    "KHMER": false,
    "ARABIC": false,
    "HAN": false
  },

改好了之后你可以输入这个指令重新载入设置

/f reload

有些脚本类型在计数方面不是很好.举个例子:



这样的话就要把最小字数限制改成0:

  "factionTagLengthMin": 0,LegacyFaction

**Comment by MarkehMe** [comment]
@mcmaxcn amazing! Thank you so much

I have published it here:
https://github.com/redstone/LegacyFactions/wiki/Multilingual-Script-Support%3A-Chinese

**Comment by MarkehMe** [comment]
I'm looking into this bug for you now :)

**Comment by MarkehMe** [comment]
Fixed, I will push a release for this soon.

**Comment by mcmaxcn** [comment]
Thanks!!All bug were fixed. Script types work well with the character count system now!

**Comment by MarkehMe** [comment]
Perfect :D Enjoy!!

**Comment by mcmaxcn** [comment]
I enable public format public chat.But the name is always white.
(I'm a member of the faction,the color should be green.)

![image](https://user-images.githubusercontent.com/30953850/29748999-e344968c-8b54-11e7-9bcc-4aab2e02ae6e.png)

![image](https://user-images.githubusercontent.com/30953850/29749000-eb436002-8b54-11e7-9f80-f91bd5d1433f.png)

And I can't disable truce chat or alliance chat.

![image](https://i.loli.net/2017/08/27/59a29df887975.png)
