### ISSUE TITLE
f show / ff command error

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#19]
Hi, I get this error using torchspigot 1.11.2 when running the command /f f or /f show

https://hastebin.com/nagevisehi.vbs

https://yivesmirror.com/downloads/torch for a copy of torch spigot, I use it cause of its advanced multi threading to lower server lag unlike all other mc servers

**Comment by MarkehMe** [comment]
@lucko any insight to this?

**Comment by DuckCraftPvP** [comment]
why you asking him?

**Comment by MarkehMe** [comment]
The error is coming from LuckPerms in VaultPermissionHook.java

**Comment by lucko** [comment]
You're passing a null player object to the vault method.

**Comment by MarkehMe** [comment]
Are you running this command from console?

**Comment by DuckCraftPvP** [comment]
no in game

**Comment by lucko** [comment]
Updated my reply.

**Comment by MarkehMe** [comment]
Weird.

Is the server running in offline mode?

**Comment by DuckCraftPvP** [comment]
bungeecord

**Comment by MarkehMe** [comment]
That should be ok. This is really weird, I need to test this myself and see if I can replicate.

**Comment by DuckCraftPvP** [comment]
kk, i send link to the jar file fyi.

**Comment by DuckCraftPvP** [comment]
i switched to regular paperspigot and got this when i ran /f fhttps://hastebin.com/yirovafefa.vbs

**Comment by DuckCraftPvP** [comment]
https://hastebin.com/suyuliwove.css

**Comment by MarkehMe** [comment]
Please try to replicate this in regular Spigot or PaperSpigot with the new error log and see if the issue still persists. These other forks are known to have odd issues with them.

**Comment by DuckCraftPvP** [comment]
https://aquifermc.org/ i got my paper spigot from these guys, AKA called paperclip. Its a updated version of paperspigot by more active authors. but sure il try to find the error again, give me a while.

**Comment by DuckCraftPvP** [comment]
f show seems to be fixed but /f unclaim still is not even on regular spigot. Seems to be a 1.12 issue.

**Comment by MarkehMe** [comment]
@DuckCraftPvP I'm looking at this again. I need you to try it in regular spigot.

This will help my understand the issue properly, as no one else has this issue. So it seems very isolated to your environment. Torch, Taco, and alternative forks are known to have issues.

If an error shows in spigot I need the new stack trace as its different :)

**Comment by DuckCraftPvP** [comment]
ok i will try it in regular spigot.

**Comment by DuckCraftPvP** [comment]
works on req spigot. seems to be a paper issue. I was using torch and taco but i decided to use paper overall, If you could add paper support that would be great.

**Comment by MarkehMe** [comment]
Could you share your latest stack trace? :)

**Comment by DuckCraftPvP** [comment]
from paper?

**Comment by MarkehMe** [comment]
Yes

**Comment by DuckCraftPvP** [comment]
This world pisses me off. This /f unclaim raidus was litt not working 5 mins ago and then i do it again on same version of paper and no error and it works? WTF? Lol, Il update if i get it in the future.

**Comment by DuckCraftPvP** [comment]
qq yep working fine now but was not earlier today. Mhh in confused.

**Comment by MarkehMe** [comment]
Sadly not sure :( but it's still something I want to investigate. 

If it pops up again, buzz this ticket :) it could have been something else to do with your permissions, vault, or who-the-hell-knows. 😞

**Comment by DuckCraftPvP** [comment]
ok will do.

**Comment by DuckCraftPvP** [comment]
i figured out what causes it. F bypass. if u have it disabled u can not /f unclaim raidus or all. so its a perm issue. it works when f bypass is enabled.

**Comment by DuckCraftPvP** [comment]
but f unclaim all dont work at all.

**Comment by DuckCraftPvP** [comment]
im having the error again. I think its a permission issue but i manually added the perms for it and it dont work.

**Comment by MarkehMe** [comment]
Okay if its happening again I need:

1) Your entire server log from start to stop (upload to [pastebin.com](https://pastebin.com/))
2) A copy of your configuration file
3) The stack trace from when the error happened
4) Since this could be permissions related, a copy of your permissions 
5) Plugin Versions + Server Version

Please fetch me that so we can work it out. Thanks!

**Comment by DuckCraftPvP** [comment]
Server log: Ignore the fatal errors. https://hastebin.com/ilirevebih.md

My config file: https://hastebin.com/ajikobigov.json
Stack Trace: None, No visible errors in console besides the /f unclaim cordinates not changing unless fbypass enabled. image of this: http://prntscr.com/fwj84j

Version: 
You are running LegacyFactions v1.4.0
This server is running Paper version git-Paper-1146 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

Permissions file: Sorta hard as its a mysql database but this link should work.
https://lpedit.lucko.me/?a24408bb2c4b6b3bbb12f24a9f34ddcd/a23ede5ec9fd8a2374951b1376102cfcbb725b08 if that does not work il get a txt version of it.

if you need anything else just msg me.

**Comment by MarkehMe** [comment]
I'm confused.

> im having the error again.

But there is no error - this is a different issue? What is the issue? 😕

**Comment by MarkehMe** [comment]
Closing because this original issue is fixed/nonexistent 😕 

I know it can be hard to get your message across sometimes 😃 , but for me to help you its important you give every detail. Because when I come back to this I'm scrolling back up and reading over everything and from my understanding you were getting stack traces but from your logs I see nothing.

**Comment by DuckCraftPvP** [comment]
i scrolled up and saw this showed error with ./f f but here. i just got this.
 https://hastebin.com/lacowiwabu.vbs

**Comment by DuckCraftPvP** [comment]
i only got stack traces from the /f f command. not from the /f unclaim system
