### ISSUE TITLE
f claim error

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#21]
I cant unclaim land in a radius or all ./f unclaimall or /f unclaim 50

https://hastebin.com/tinasexubi.vbs

it looks like it works but it dont, it only unclaims 1 chunk instead of all or 50 chunks.

also i updated my last error that should help fix it ez.

**Comment by DuckCraftPvP** [comment]
console says this: https://hastebin.com/yeyodifeve.md :P

**Comment by DuckCraftPvP** [comment]
unclaims the same chunk x 50

**Comment by MarkehMe** [comment]
Duplicate of #19

**Comment by DuckCraftPvP** [comment]
its not a duplicate, one is /f show and 1 is /f unclaim radius

**Comment by MarkehMe** [comment]
They are the same error caused by the same thing. :)

**Comment by DuckCraftPvP** [comment]
oh, Well when will it be fixed?
