### ISSUE TITLE
Per-faction autoleave

### ISSUE THREAD

**Issue by TheWranger** [redstone/LegacyFactions#213]
Add a command for leaders to set a custom autoleave (thing that kicks players after they're inactive for X days). Something like "/f autokick X" (where X is the amount of days tiill they inactive players get kicked). It should also default to 0 (disabled) for every faction.

Also add a config option like "useoldautoleave: false/true" that defaults to false (duh) and when set to true, uses the old server-wide autoleave system (aka the one that's currently implemented).

**Comment by TheWranger** [comment]
yes botman

**Comment by MarkehMe** [comment]
Sounds good!

**Comment by MarkehMe** [comment]
I'm going to put this in 1.5 :)

**Comment by MarkehMe** [comment]
Also introduces permissions:
* factions.autokick
* factions.autokick.others
