### ISSUE TITLE
Error with player's first join related to scoreboard not working (Please fix)

### ISSUE THREAD

**Issue by Spazzinq** [redstone/LegacyFactions#23]
TacoSpigot: [https://hastebin.com/dutaqafozi.vbs](https://hastebin.com/dutaqafozi.vbs)

Recreated in PaperSpigot 1.8.8: [https://gist.github.com/Spazzinq/381f5f12687b078144df85cb302c57b3](https://gist.github.com/Spazzinq/381f5f12687b078144df85cb302c57b3)

Recreated in Spigot 1.8.8: [https://gist.github.com/Spazzinq/322f7f70dedfdd7bf6c77119dff5dd7d](https://gist.github.com/Spazzinq/322f7f70dedfdd7bf6c77119dff5dd7d)

Recreated in Spigot 1.12 [https://hastebin.com/dowarayupo.bash](https://hastebin.com/dowarayupo.bash)

My current scoreboard config:
[https://hastebin.com/gefuyicowa.sm](https://hastebin.com/gefuyicowa.sm)

Edited for much clearer layout and information

**Comment by Spazzinq** [comment]
P.S. Please add /f truce and include truce chat in the rotation of /f chat ! Thanks!

**Comment by MarkehMe** [comment]
Please try recreate this in regular Spigot, or at least Paper. There has been several reports of issues with TacoSpigot.

**Comment by Spazzinq** [comment]
Recreated in PaperSpigot: [https://gist.github.com/Spazzinq/381f5f12687b078144df85cb302c57b3](https://gist.github.com/Spazzinq/381f5f12687b078144df85cb302c57b3)

Recreated in Spigot: [https://gist.github.com/Spazzinq/322f7f70dedfdd7bf6c77119dff5dd7d](https://gist.github.com/Spazzinq/322f7f70dedfdd7bf6c77119dff5dd7d)

**Comment by Spazzinq** [comment]
@MarkehMe :)

**Comment by Spazzinq** [comment]
This issue happens to the first player to join the server and I also believe has to do with my scoreboard not working

**Comment by MarkehMe** [comment]
Thanks! I do request you try in the latest spigot as well (1.12) if it works in that, then we know it's a 1.8 related bug. In which I should be able to find a quick really quickly! 😄

**Comment by Spazzinq** [comment]
I spent 20 minutes compiling the latest 1.12 and the error is still thrown.. xD [https://hastebin.com/dowarayupo.bash](https://hastebin.com/dowarayupo.bash)

**Comment by Spazzinq** [comment]
@MarkehMe

**Comment by MarkehMe** [comment]
@Spazzinq Did you try this in 1.12?

**Comment by Spazzinq** [comment]
@MarkehMe Read the top post xD I reordered it yesterday and you missed it xd

**Comment by Spazzinq** [comment]
Recreated in Spigot 1.12 https://hastebin.com/dowarayupo.bash

**Comment by ctooley21** [comment]
I will look into this tomorrow for you. Would you mind sending me a copy of your LegacyFaction files? Jar & Folder if possible.

**Comment by ctooley21** [comment]
@Spazzinq Should be fixed now, mind testing and letting me know if you have any issues?
https://www.dropbox.com/s/ukxq75kuubtcbn7/LegacyFactions-1.3.0-all.jar?dl=0

**Comment by Spazzinq** [comment]
@ctooley21 works without any issues! Thanks :D

**Comment by ctooley21** [comment]
No problem!

**Comment by ctooley21** [comment]
@MarkehMe closed 😄
