### ISSUE TITLE
Co-Leader Role

### ISSUE THREAD

**Issue by BajanPlaysGames** [redstone/LegacyFactions#24]
Could you add a Co-Leader role to factions roles like the Leader Would have 3 starts *** then Co-Leader ** Then Mod * then Officer + Then member - then recruit (no tag) A little like on cosmic pvp. I would love to see this thanks.

**Comment by DuckCraftPvP** [comment]
agreed

**Comment by MarkehMe** [comment]
We've just been discussing this and we've begun planning it :) 

A permission will be added so that server that don't want co-leaders can disable it.
