### ISSUE TITLE
Placeholder API 2.8.0 support

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#27]
Hi, can you add placeholder api 2.8.0 support? he made it so u can add color changing place holders
https://www.spigotmc.org/resources/placeholderapi.6245/updates

2.8.0 
[​IMG] ​

Added the ability for expansions to provide relational placeholders. These types of placeholders can show information specific to the relation between 2 players. A good example would be the relation between 2 factions:
[​IMG]
PlaceholderAPI does not automatically parse relational placeholders on its own when normal placeholders are parsed!. Plugins which would want to utilize these placeholders will need to update and call the new method to parse relational placeholders:
Code (Java):
PlaceholderAPI.setRelationalPlaceholders(Player one, Player two, String message);
End users will need to specify the relational placeholders with a specific format:
Code (Text):
%rel_<placeholder>%
Note, only placeholders created specifically for relation based values will work. %rel_player_name% wouldn't work as that is a normal placeholder but %rel_factions_relation_color% would work as it is a valid relational placeholder.

For developers to add this functionality in expansions. Here is a brief example of an expansion suited for relational placeholders:
Code (Java):
public class RelationalExpansion extends PlaceholderExpansion implements Relational {

    @Override
    public boolean canRegister() {
        return true;
    }

    @Override
    public String getAuthor() {
        return "clip";
    }

    @Override
    public String getIdentifier() {
        return "player";
    }

    @Override
    public String getPlugin() {
        return null;
    }

    @Override
    public String getVersion() {
        return "1.0.0";
    }

    @Override
    public String onPlaceholderRequest(Player p, String s) {
        // %player_name%
        if (s.equals("name")) {
            return p.getName();
        }
        return null;
    }

    @Override
    public String onPlaceholderRequest(Player one, Player two, String identifier) {
        // %rel_player_distance%
        if (identifier.equals("distance")) {
            return String.valueOf(one.getLocation().distance(two.getLocation()));
        }
        return null;
    }
}
Placeholder expansions will now be automatically loaded when /papi ecloud download <expansion> is executed. No more need to use /papi reload afterwards.

Added a config option to automatically download and register missing expansions when a placeholder is used that is not currently registered. if the expansion exists on the cloud.
[​IMG]
This will be set to true by default.

Added 1.12 to the NMSVersion enum.

**Comment by MarkehMe** [comment]
Sure, should be fine to add.

**Comment by DuckCraftPvP** [comment]
Thank you :)

**Comment by DuckCraftPvP** [comment]
any idea a eta on this update?

**Comment by Spazzinq** [comment]
@DuckCraftPvP I never really understood how to use this with name tags. Could you reach me xD

**Comment by DuckCraftPvP** [comment]
nametags?

**Comment by Spazzinq** [comment]
Yeah like on their name tag. Is there a way to do that?

**Comment by Spazzinq** [comment]
No, like faction relation colors in the nametag

**Comment by DuckCraftPvP** [comment]
Oh you cant as of currently. I asked him to add support for that. Thats what this post is about.

**Comment by Spazzinq** [comment]
Oh, okay. My misunderstanding. Thanks for clearing it up.

**Comment by MarkehMe** [comment]
It's on the pipeline, and is a high priority addition :)

**Comment by DuckCraftPvP** [comment]
yay so next update is next year? jking xD keep up good work but would love to see a update soon. At least to fix teh bugs with unclaiming land.

**Comment by MarkehMe** [comment]
I will implement this in the next release. 💃

**Comment by DuckCraftPvP** [comment]
yay!!! so 5 seconds from now?

**Comment by DuckCraftPvP** [comment]
joking. i know you need time. Sorry im inpatient.

**Comment by MarkehMe** [comment]
😛 Thats the dream isn't it? 🤣

**Comment by DuckCraftPvP** [comment]
ikr xD

**Comment by MarkehMe** [comment]
Fixed in #72
