### ISSUE TITLE
Suggestions and request

### ISSUE THREAD

**Issue by dan330330** [redstone/LegacyFactions#28]
First thing I would love deluxechat support. Feature requests:
1- Make a /fly only in faction a feature
2- Add selection of permitted commands in neutral and enemy faction and slog in neutral and enemy faction tp to spawn or a selected position
3- Built in /f top
4- Upgradable faction in gui like potion effect in your faction or ally territory; upgrading to add more members, allys, enemys; upgrading to add more faction power and more..
5- Make a claiming price withing a selected chunk close to the warzone
That is all for now and sorry for my bad english. If you see this I need badly those features and I think this would make your plugin unique and reaply to me thanks for reading.

**Comment by dan330330** [comment]
One more thing you could add a faction warps and add a gui to it with this you could add an upgrade like mentioned before so you can have more faction warps.

**Comment by DuckCraftPvP** [comment]
There is a built in /f top and /fly in fact land is a addon request someone else to make it. update gui is the same thing.

**Comment by DuckCraftPvP** [comment]
also dan is /f unclaim radius working for you?

**Comment by dan330330** [comment]
Nope

**Comment by MarkehMe** [comment]
In the future please create a seperate issue for each feature - as its quite hard to keep ontop of them all.

The following already exists:
* /f top

The following have been moved into seperate issues:
* Faction Fly: #40
* Land Based Permission: #41
* Upgrades: #42
* Land Value: #43
