### ISSUE TITLE
Color code issues

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#38]
Hello, Color codes do not update in faction description.
http://prntscr.com/fw11b7

same for description
http://prntscr.com/fw11oy

**Comment by DuckCraftPvP** [comment]
nvm. Color codes was off in the config. works now with it enabled.

**Comment by MarkehMe** [comment]
Great to hear :) enjoy!

**Comment by DuckCraftPvP** [comment]
Just cant wait till placeholderapi update! Please asap!
