### ISSUE TITLE
Scoreboard Issues

### ISSUE THREAD

**Issue by Spazzinq** [redstone/LegacyFactions#39]
The scoreboard doesn't seem to be updating, leaving the variables I have on them useless. Could you please fix the scoreboard updating? Also, when you stop your server, it replaces the placeholders that you had in the config with the actual parsed placeholders of the player. If you could fix these issues, that would be awesome :)

P.S. 2nd Issue ONLY for scoreboardDefault and not scoreboardFactionless for some reason. The placeholder isn't replaced with the parsed placeholder on the scoreboardFactionless. Also, I used the placeholders {faction} {chunks} {power} and {balance}.

Version tested: TacoSpigot 1.8.8,
No thrown errors

**Comment by MarkehMe** [comment]
Hi! Thanks for reporting. Lets go over a few things first to try and work out whats going on :) 

---

# 1. Can you share your configuration?
This will help us see whats going on.

# 2. What options have you changed?
If you can compare to the original options this well help. Maybe also try setting back to a clean configuration, and only enabling scoreboards. 

# 3. Can you explain a bit further on the placeders?
> when you stop your server, it replaces the placeholders that you had in the config with the actual parsed placeholders of the player

What placeholders? What configuration options? Please walk through this with me.

---

Hopefully we can sort this out quickly 💃

**Comment by Spazzinq** [comment]
# 1. Can you share your configuration?

[https://gist.github.com/Spazzinq/1c23f02fde74be01e93e77c15b447e31](https://gist.github.com/Spazzinq/1c23f02fde74be01e93e77c15b447e31)

# 2. What options have you changed?

Config above

> If you can compare to the original options this well help. Maybe also try setting back to a clean configuration, and only enabling scoreboards.

Reset to original, still doesn't update

# 3. Can you explain a bit further on the placeholders?

> What placeholders? What configuration options? Please walk through this with me.

Placeholders I used were in first post and config I have put into a gist.

**Comment by Spazzinq** [comment]
@MarkehMe

**Comment by MarkehMe** [comment]
_No need to tag me I get an email for every message/action in this repo :)_ 

Thanks for that. We're investigating it this week.

**Comment by Spazzinq** [comment]
Okay, thanks :)

**Comment by MarkehMe** [comment]
@Spazzinq would you be ok with doing some testing for us on this bug? Do you have [discord](https://discord.gg/p3VjnUd)?

**Comment by Spazzinq** [comment]
@MarkehMe Of course! I'm in the discord :)

**Comment by Spazzinq** [comment]
Okay, nevermind the parsed placeholder DOES replace the placeholder in scoreboardFactionless, but with 0 unless you /f reload.

**Comment by Spazzinq** [comment]
The default scoreboard replaces the placeholders with the parsed placeholders upon players logout

**Comment by MarkehMe** [comment]
Fixed. Will be in v1.4.1. 💃  🎉
