### ISSUE TITLE
Faction top and more

### ISSUE THREAD

**Issue by dan330330** [redstone/LegacyFactions#51]
Hi developer I loved that you moved my suggestion in work and I would love to suggest you another unique thing to make more changes from the "old" faction plugins. 
1- Make an f top in gui so all the faction are shown from the best to the worst and add a filter option so you can filter the faction that is at exaple better in money or better in spawner value and ecc.. you could make this a on/off in the config
2- If you are working with the upgrade gui you could add to it a /f fly so if you buy it players in that faction can fly in there faction and that you can upgrate it untill you can fly even in ally territory
3- You could add a /f banner so people can create banners for the faction and the banner can be seen in the /f top like mentioned before in gui
4- I would up the vote for the claim value close to the warzone
5- Add to the upgrade gui in work effects that you can buy for your faction and if players do /f effect it shows a gui so they can enable/disable effects bought from the faction so it doesn t messup effects that they use with potions 
6- Last request upvote for the /f banner for sobstitute but changed to /f sos so doesn t messup my other /f banner request 

Thanks for reading hope to see this features soon if you like it but can t/ don t wanna add it msg me here! Sorry for my bad english.

**Comment by MarkehMe** [comment]
Hi can you confirm this is what you're after:

1) GUI for `/f top`. But can you explain this filter option further? How should it look?
2) Do you mean adding permissions to the upgrade menu listed in #42?
3) This is already requested in #46 - we can probably combine it :) 
4) Sure, it seems like a great idea. #43
5) Can you explain this further - perhaps provide a few examples? :)
6) That might be better - it should include a warmup/cooldown too

**Comment by dan330330** [comment]
Ok thank you I ll make some gifs or videos to explain all better

**Comment by dan330330** [comment]
Lol clicked the wrong thing sorry

**Comment by dan330330** [comment]
Sorry that is tanking a bit but my computer is a bit slow this day gonna show you all in those days

**Comment by MarkehMe** [comment]
No worries mate. :)

**Comment by dan330330** [comment]
Mate I am almost done! Hope this features will come out =D

**Comment by dan330330** [comment]
https://youtu.be/FdpzxfEtSB8 this is the video for the 1st idea =D

**Comment by dan330330** [comment]
1 thing you could add is spawner top!

**Comment by dan330330** [comment]
Can I explain the 2- With a Gui too?

**Comment by dan330330** [comment]
And 5- too?

**Comment by dan330330** [comment]
@MarkehMe could you respond to this xD

**Comment by MarkehMe** [comment]
@dan330330 sorry for the late response!! 🤗 

We need to keep ideas organised - not just in one issue - otherwise I'll forget about it or the ideas will get lost! 😆 

So number 1 please open a new issue as "gui for /f top"

So number 2 and 5 you should keep to issue #42 please, as its to do with the upgrades. 

Number 3 in #46

Number 4 in #43

etc :) 

And open a new issue for each of the others :) 

I'm going to close this issue but hopefully that makes sense? Try to keep 1 issue = 1 feature 😄

**Comment by dan330330** [comment]
No problem understood all gonna make as u sad!
