### ISSUE TITLE
Factionless Board Replacing Placeholders With 0

### ISSUE THREAD

**Issue by Spazzinq** [redstone/LegacyFactions#53]
I put the placeholder {money} , and it gets replaced with 0 in the config.

**Comment by MarkehMe** [comment]
Is it only `{money}`?

**Comment by Spazzinq** [comment]
Nope, its replacing all number related placeholders with 0, e.x: {power} (also I forgot its {balance} not {money}).

**Comment by Spazzinq** [comment]
Works if you /f reload

**Comment by MarkehMe** [comment]
Fixed. Will be in v1.4.1. 💃  🎉
