### ISSUE TITLE
Claim Message Change

### ISSUE THREAD

**Issue by Spazzinq** [redstone/LegacyFactions#54]
Change the claim message to chunks claimed instead of one by one spam of each chunk claimed

**Comment by MarkehMe** [comment]
This is a cool idea. The option could be called `enableShorterTransactionMessage`

Perhaps an option to click on the text highlighted like this:

<img width="443" alt="screen shot 2017-07-23 at 3 57 44 pm" src="https://user-images.githubusercontent.com/1357323/28497040-b89f27cc-6fbf-11e7-8e71-0cb8108180e6.png">

Would then show a list of chunks claimed (incase they really wanted to know)

**Comment by dan330330** [comment]
Up that! Also I m making the gifs for the more information of my feature

**Comment by MarkehMe** [comment]
This fix also includes a new non-blocking async spiral task. So we can calculate all the chunks in a radius without blocking the game. AKA less-lag on large radius claims!
