### ISSUE TITLE
{player-balance} Placeholder in tooltips doesn't work

### ISSUE THREAD

**Issue by Spazzinq** [redstone/LegacyFactions#56]
Loadup (no errors)
https://gist.github.com/Spazzinq/a4bbbee41c8514abe6672861a1a51618

Version: 1.8.8 TacoSpigot

**Comment by MarkehMe** [comment]
Should be fixed, but I need confirmation in a test build.

**Comment by Spazzinq** [comment]
Fixed ✅

**Comment by MarkehMe** [comment]
Great!
