### ISSUE TITLE
PlaceHolders

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#6]
Place holders dont work

http://prntscr.com/f8x1cr

**Comment by MarkehMe** [comment]
Hi! 

Could you share the startup log for LegacyFactions?

**Comment by DuckCraftPvP** [comment]
sure

**Comment by DuckCraftPvP** [comment]
https://hastebin.com/ojibocazes.md

**Comment by MarkehMe** [comment]
Can you add me on Skype so we can try a few things? :)

Skype: markehme

**Comment by MarkehMe** [comment]
Fixed :)
