### ISSUE TITLE
Dev Api

### ISSUE THREAD

**Issue by HyperBlueCore** [redstone/LegacyFactions#62]
Do you have any dev api?

**Comment by MarkehMe** [comment]
Sure do.

Events are here: https://github.com/redstone/LegacyFactions/tree/master/src/main/java/net/redstoneore/legacyfactions/event

For working with entities you can `FPlayerColl.get(player / name / uuid)` or `FactionColl.get(faction name / facitonid / player /fplayer)`

see:
https://github.com/redstone/LegacyFactions/tree/master/src/main/java/net/redstoneore/legacyfactions/entity

Theres some info here on the wiki too:
https://github.com/redstone/LegacyFactions/wiki/API

Although its incomplete (i'm working on it though!)

**Comment by MarkehMe** [comment]
Here is some in depth stuff too about Factions (still also working on FPlayers doc etc - but its all the the interfaces if you need specific stuff):

https://github.com/redstone/LegacyFactions/wiki/API:-Factions

Feel free to [jump on our discord](https://discord.gg/p3VjnUd) and ask questions :)
