### ISSUE TITLE
Faction Armor Stand Protection

### ISSUE THREAD

**Issue by TheWranger** [redstone/LegacyFactions#64]
Armor Stands are detected as entities instead of blocks, so they aren't currently protected.

**Comment by MarkehMe** [comment]
Wow, this is critical. Thanks for reporting. It'll be in the next release.

**Comment by TheWranger** [comment]
Maybe have like a config option "ProtectArmorStand" or something like that.

**Comment by MarkehMe** [comment]
Fixed in 1.4.2
