### ISSUE TITLE
Permission Changes/Additons

### ISSUE THREAD

**Issue by TheWranger** [redstone/LegacyFactions#66]
factions.setpeaceful should be cut into two permissions:
 factions.setpeaceful: Changing own faction into a peaceful faction.
 factions.setpeaceful.any: Changing other factions peaceful status.
 The same could be done for factions.setpermanent and factions.setpermanentpower

**Comment by MarkehMe** [comment]
Great. I agree!

**Comment by MarkehMe** [comment]
Fixed with new .set permissions (to be documented)
