### ISSUE TITLE
Wild rework

### ISSUE THREAD

**Issue by dan330330** [redstone/LegacyFactions#69]
I know that your plugin supports wildtp but it doesnt perform good and it has bugs I would suggest a wild rework like this:
1- /wild would bring up a gui that you can select what world you would go to making a multiverse support mabe selecting what worlds in the config
2- When you select the world it could bring up another gui to select how distant from the spawn it would tp and make cost for it so players wont spam it at exaple: 1000-2500 block from spawn cost in the config and the distance in the config
3- No tp in a base or near like 5 chunk or set in the config from it
4- Mabe /f upgrade support so you can buy what world you can go in? 

Sorry for all the gui request for your plugin I know it is hard to do keep up the work and tell me if you can or cant do this!

**Comment by MarkehMe** [comment]
We don't actually make the wild plugin. You will have to ask those developers to do it :) 

The `/f upgrade` will support permission groups though. So you could use permissions for that.

**Comment by dan330330** [comment]
ok thx!

**Comment by MarkehMe** [comment]
Awesome! Good luck 🕺
