### ISSUE TITLE
HD Error

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#7]
Found a spammy error with holographic displays. Really annoying, The amount of console spam makes server lag. Had to temp remove the hd plugin.

https://hastebin.com/wesixexeri.vbs

**Comment by MarkehMe** [comment]
There was a bug where some placeholders required a player, and because in HD there is no player associated with a placeholder on HD - it would throw an error. 

Although it wouldn't break LegacyFactions it would spam the console a lot.

**Comment by DuckCraftPvP** [comment]
yea cept the fact that the spam is soo much that it lags my server lol. Im using .bat consoles and it is doing like 300 of those errors a second.

**Comment by MarkehMe** [comment]
I have released this update:

https://github.com/redstone/LegacyFactions/releases/tag/v1.2.2

**Comment by DuckCraftPvP** [comment]
ok, Thx
