### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by dan330330** [redstone/LegacyFactions#70]
29.07 12:13:30 [Server] WARN ... 18 more
29.07 12:13:30 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
29.07 12:13:30 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
29.07 12:13:30 [Server] WARN at java.lang.Class.forName(Unknown Source)
29.07 12:13:30 [Server] WARN at java.lang.Class.forName0(Native Method)
29.07 12:13:30 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
29.07 12:13:30 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
29.07 12:13:30 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
29.07 12:13:30 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
29.07 12:13:30 [Server] WARN at java.net.URLClassLoader.findClass(Unknown Source)
29.07 12:13:30 [Server] WARN at java.security.AccessController.doPrivileged(Native Method)
29.07 12:13:30 [Server] WARN at java.net.URLClassLoader$1.run(Unknown Source)
29.07 12:13:30 [Server] WARN at java.net.URLClassLoader$1.run(Unknown Source)
29.07 12:13:30 [Server] WARN at java.net.URLClassLoader.access$100(Unknown Source)
29.07 12:13:30 [Server] WARN at java.net.URLClassLoader.defineClass(Unknown Source)
29.07 12:13:30 [Server] WARN at java.security.SecureClassLoader.defineClass(Unknown Source)
29.07 12:13:30 [Server] WARN at java.lang.ClassLoader.defineClass(Unknown Source)
29.07 12:13:30 [Server] WARN at java.lang.ClassLoader.defineClass1(Native Method)
29.07 12:13:30 [Server] WARN Caused by: java.lang.UnsupportedClassVersionError: net/redstoneore/legacyfactions/Factions : Unsupported major.minor version 52.0
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:789)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:883)
29.07 12:13:30 [Server] WARN at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1046)
29.07 12:13:30 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:766)
29.07 12:13:30 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
29.07 12:13:30 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
29.07 12:13:30 [Server] WARN at com.jadeningle.PluginManager.PluginManagerCommand.onCommand(PluginManagerCommand.java:59)
29.07 12:13:30 [Server] WARN at com.jadeningle.PluginManager.PluginManagerCommand.loadPluginCommand(PluginManagerCommand.java:161)
29.07 12:13:30 [Server] WARN at com.jadeningle.PluginManager.Utils.Control.loadPlugin(Control.java:130)
29.07 12:13:30 [Server] WARN at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336)
29.07 12:13:30 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
29.07 12:13:30 [Server] WARN org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/redstoneore/legacyfactions/Factions : Unsupported major.minor version 52.0

**Comment by dan330330** [comment]
Srry paperspigot

**Comment by MarkehMe** [comment]
I can't really read this on my phone but judging by the last line 
Unsupported major.minor version 52.0
You may need to install Java 8 

Please put logs onto pastebin!

**Comment by MarkehMe** [comment]
Yep just checked it properly. Your version of Java is outdated.

Here are some links to help you:

- [Linux Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/install/linux_jre.html#CFHBJIIG) 
- [Mac Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jre.html#CHDGECEB)
- [Windows Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/install/windows_jre_install.html#CHDEDHAJ) 
 
😄

**Comment by dan330330** [comment]
Ok thanks I was just on a friends server so I wanted to help him
