### ISSUE TITLE
API: Find a faction by location

### ISSUE THREAD

**Issue by kangarko** [redstone/LegacyFactions#75]
Hello,

I recently got a request for a plugin and so I was wondering whether it is possible for a developer to easily find a Faction by a location in a world, similarly to "BoardColl.get().getFactionAt()" method by the mcore Factions plugin.

Thanks!

**Comment by MarkehMe** [comment]
Sure! 

Okay so you need to wrap the location/chunk/whatever first. Similar to PS that MassiveCore uses:

```java
FLocation flocation = FLocation.valueOf(chunk or location);
```

Now you can use this:
```java
Faction faction = Board.get().getFactionAt(flocation);
```

Here are some helpful classes for you:
- [FLocation](https://github.com/redstone/LegacyFactions/blob/master/src/main/java/net/redstoneore/legacyfactions/FLocation.java)
- [Board](https://github.com/redstone/LegacyFactions/blob/master/src/main/java/net/redstoneore/legacyfactions/entity/Board.java)
- [Faction](https://github.com/redstone/LegacyFactions/blob/master/src/main/java/net/redstoneore/legacyfactions/entity/Faction.java)

Hope that helps!! 😄 If you want, feel free to [jump on discord](https://discord.gg/p3VjnUd) and ask questions directly. 💃

**Comment by MarkehMe** [comment]
P.S. my goal is to be super developer friendly, so if you have any suggestions please let me know :)

**Comment by kangarko** [comment]
Amazing! Thanks for being super friendly and I just took a huge inspiration about how to provide user service haha :) 

Works!

Best of luck.

**Comment by MarkehMe** [comment]
No worries! 

Feel free to open another issue if you need help - or even message me directly on discord if you need in depth help (or even a little) 🕺 

Enjoy the rest of your day/night 😃

**Comment by kangarko** [comment]
Thanks Markeh I really appreciate it!
