### ISSUE TITLE
Title time shown issue

### ISSUE THREAD

**Issue by Spazzinq** [redstone/LegacyFactions#82]
The defaults you have for the fadeIn, stay, and fadeOut (two) are measured in ticks shown and it is really short so you might want to change it to 10 fadeIn, 50 stay, and 10 fadeOut which I tested that look nice.

**Comment by MarkehMe** [comment]
I should rename the option to include "ticks" so it makes a bit more sense too

**Comment by Spazzinq** [comment]
Yeah, I kinda meant to explain that

**Comment by MarkehMe** [comment]
Fixed
