### ISSUE TITLE
Placeholder issues with 1.4.1

### ISSUE THREAD

**Issue by Buddhano** [redstone/LegacyFactions#84]
Same issue as mentioned [here](https://github.com/redstone/LegacyFactions/issues/55#issuecomment-318897101) persists in 1.4.1

Same placeholders are loaded in the startup as in my config, I've tried using %s and brackets to no avail.

I've tried putting mvdw_ before each placeholder as well

**Comment by MarkehMe** [comment]
Please show an example of the placeholders you're using

**Comment by Buddhano** [comment]
This is in my tablist config. None of them load in-game
`        &b&l&o%mvdw_factions_player_role_prefix%{factions_player_role}%factions_player_title% %player%
        &7Faction: &2&l&o%factions_faction_name%
        &a&l%factions_faction_description%
        &7Power: &2%factions_faction_power%&7/&2%factions_faction_powermax%
        &7Factions K/D: &2%factions_player_kills%&7/&2%factions_player_deaths%`

**Comment by Buddhano** [comment]
I'm using PlaceholderAPI and mvdwplaceholderapi. could there be a compatibility issue there?

**Comment by MarkehMe** [comment]
How does it render? Can you show a screenshot?

**Comment by Buddhano** [comment]
http://i.imgur.com/PN4hyjO.jpg

**Comment by MarkehMe** [comment]
Sorry I misread this.

This has been fixed in v1.4.2, the upcoming release.

**Comment by MarkehMe** [comment]
If you want you can jump into #testers on [our discord](https://discord.gg/p3VjnUd) and grab a development build. We'd love feedback, it doesn't have any bugs that I'm aware of (yet).

https://discord.gg/p3VjnUd

**Comment by Buddhano** [comment]
Fixed with 1.4.2
