### ISSUE TITLE
Server Crashing on boot up.

### ISSUE THREAD

**Issue by Xrey274** [redstone/LegacyFactions#86]
When i put the latest version of LegacyFactions in my server it crashes. At first i was like: "Ok why can't i connect to my server." Then i looked at the console..it was flooded with errors. (Tell me if i need to provide anymore information regarding the problem.)

Lates Crash Report: https://www.dropbox.com/s/glq5xr8brllw2ov/latest.log?dl=0

**Comment by MarkehMe** [comment]
You aren't using LegacyFactions.

```
[16:28:17] [Server thread/INFO]: [Factions] Loading Factions v2.13.0-SNAPSHOT
```

**Comment by Xrey274** [comment]
Oops wrong file!

**Comment by Xrey274** [comment]
https://www.dropbox.com/s/glq5xr8brllw2ov/latest.log?dl=0
