### ISSUE TITLE
LegacyFaction Crashing Server

### ISSUE THREAD

**Issue by Xrey274** [redstone/LegacyFactions#87]
When i put the latest version of LegacyFactions in my server it crashes. At first i was like: "Ok why can't i connect to my server." Then i looked at the console..it was flooded with errors. (Tell me if i need to provide anymore information regarding the problem.)

Lates Crash Report: https://www.dropbox.com/s/glq5xr8brllw2ov/latest.log?dl=0

**Comment by Xrey274** [comment]
This is a repost, because the previous had a wrong link and was closed.

**Comment by MarkehMe** [comment]
Look I'm going to be honest with you.. there is a lot of issues in here but nothing points to LegacyFactions. LegacyFactions is loading fine. 

However you have a lot of issues going on here. It's really concerning. 

1. You need to first fix your broken plugins:
```
[14:15:47] [Server thread/ERROR]: Could not load 'plugins/Shopkeepers.jar' in folder 'plugins'
[14:15:48] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit.jar' in folder 'plugins'
```
(replace them or remove them) 

2. SexyMotd is broken. If you read your errors logs:
```
[14:15:56] [Netty Server IO #18/ERROR]: [SexyMotd] Unhandled exception occured in onPacketSending(PacketEvent) for SexyMotd
```

3. So is SuperVanish
```
[14:16:04] [Netty Server IO #21/ERROR]: [SuperVanish] Unhandled exception occured in onPacketSending(PacketEvent) for SuperVanish
```

4. It's also not a full console log?

5. But I really suggest removing SexyMotd and SuperVanish as by reading the logs it's doing stuff with packets and is broken.

**Comment by Xrey274** [comment]
MarkehMe - 1. Here's the new log file - https://www.dropbox.com/s/zt302958mgzuxb7/2017-08-04-7.log?dl=0 2. Please don't close the threat after you read it, please wait for me to respond. 3. Removed all the plugin you told me to. Server still crashes..

**Comment by MarkehMe** [comment]
The server crashed from FactionsTop
