### ISSUE TITLE
No Message Given When Unclaiming Land

### ISSUE THREAD

**Issue by KAMKEEL** [redstone/LegacyFactions#9]
When you /f unclaim, the message in console appears that notifies and logs that a player has unclaimed land. However the player unclaiming the land does not receive a message that lets the user know that they have unclaimed land.

**Comment by MarkehMe** [comment]
What server version are you using?

**Comment by MarkehMe** [comment]
**Fixed in v1.3.0**

https://github.com/redstone/LegacyFactions/releases/tag/v1.3.0
