### ISSUE TITLE
Add option to make Wilderness show nothing on placeholder

### ISSUE THREAD

**Issue by Spazzinq** [redstone/LegacyFactions#90]

**Comment by MarkehMe** [comment]
Could you elaborate on this a little more? 

Do you mean `{factions_faction_description}` just returns a blank string?

**Comment by Spazzinq** [comment]
I meant it for the {factions_faction_name} placeholder

**Comment by MarkehMe** [comment]
Where do you want it to be blank? Because if I blank the placeholder it will go blank everywhere.

**Comment by Spazzinq** [comment]
I just want the placeholder {factions_faction_name} to show nothing if they don't have a faction. Hope that clears up our confusion :)

**Comment by MarkehMe** [comment]
New placeholders:
* factions_faction_name_blankwild
* factions_faction_description_blankwild
